name: TD-Table CI

on:
  pull_request:
    branches:
      - feat/percy-integration

jobs:
  ci:
    strategy:
      matrix:
        shard: [1, 2]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Install browsers for Playwright
        run: yarn playwright install --with-deps

      - name: Build project
        run: yarn build

      - name: Run Storybook
        id: storybook
        run: |
          npx serve -l 3000 storybook-static/ &
          echo "pid=$!" >> $GITHUB_ENV

      - name: Wait for Storybook
        uses: ./actions/wait-for-it
        with:
          URL: "http://localhost:3000"
          timeout-minutes: 3

      # Percy visual regression tests
      - name: Run Percy Storybook
        working-directory: storybook-static
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: yarn percy storybook http://localhost:3000

      - name: Stop Storybook
        run: kill ${{ env.pid }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: .playwright
