name: TD-Table CI

on:
  pull_request:
    branches:
      - feat/percy-integration

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Install browsers for Playwright
        run: yarn playwright install --with-deps

      - name: Build project
        run: yarn build

      - name: Build Storybook
        run: yarn build-storybook

      - name: Start Storybook
        id: storybook
        run: |
          npx serve -l 3000 ./storybook-static &
          echo "pid=$!" >> $GITHUB_ENV

      - name: Wait for Storybook to be Ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Storybook is up!"
              break
            else
              echo "Waiting for Storybook..."
              sleep 6
            fi
          done

      # Run Percy with Storybook
      - name: Run Percy Visual Tests
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }} # Percy token set in GitHub Secrets
        run: |
          percy exec -- yarn percy snapshot ./storybook-static

      - name: Stop Storybook
        run: kill ${{ env.pid }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: .playwright
