name: Percy Visual Regression Testing

on:
  pull_request:
    branches:
      - feat/percy-integration

jobs:
  visual-regression:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: yarn install

      # 4. Build Storybook
      - name: Build Storybook
        run: yarn build-storybook

      # 5. Install Percy CLI (global) for GitHub CI
      - name: Install Percy CLI
        run: yarn global add @percy/cli

      # 6. Run Percy with Storybook
      - name: Run Percy visual tests
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }} # Percy token set in GitHub Secrets
        run: |
          percy exec -- yarn serve storybook-static &
          sleep 5 # Give it some time to start
          percy snapshot ./storybook-static

      # 7. Optional: Upload test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: percy-test-results
          path: ./storybook-static
