name: Percy Visual Regression Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  visual-regression:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: yarn install

      # 4. Build Storybook
      - name: Build Storybook
        run: yarn build-storybook

      # 5. Generate Storybook URLs
      - name: Generate Storybook URLs
        run: node scripts/storybookUrls.js

      # 6. Install Percy CLI (global) for GitHub CI
      - name: Install Percy CLI
        run: yarn global add @percy/cli

      # 7. Run Percy with Storybook
      - name: Run Percy visual tests
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }} # Percy token set in GitHub Secrets
        run: |
          while IFS= read -r url; do
            percy snapshot "$url"
          done < storybook-urls.txt
